[package]
name = "news-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.news-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.6"
default-features = false
